-- Generated by scripts/bundle-sql.js — do not edit by hand
-- Edit src/api/sql/*.sql and run: npm run bundle-sql

PRAGMA foreign_keys = ON;

-- shkafchik schema v1

CREATE TABLE IF NOT EXISTS Categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  parent_id INTEGER,
  date_created TEXT DEFAULT CURRENT_TIMESTAMP,
  date_modified TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_id) REFERENCES Categories (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ItemStatuses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  description TEXT
);

CREATE TABLE IF NOT EXISTS Colors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  hex_code TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  category_id INTEGER NOT NULL,
  status_id INTEGER NOT NULL,
  is_favorite INTEGER DEFAULT 0,
  date_created TEXT DEFAULT CURRENT_TIMESTAMP,
  date_modified TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES Categories (id) ON DELETE RESTRICT,
  FOREIGN KEY (status_id) REFERENCES ItemStatuses (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  item_id INTEGER,
  file_path TEXT NOT NULL,
  display_order INTEGER DEFAULT 0,
  FOREIGN KEY (item_id) REFERENCES Items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Attributes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  item_id INTEGER,
  attribute_type TEXT NOT NULL,
  value TEXT,
  FOREIGN KEY (item_id) REFERENCES Items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  color_id INTEGER,
  FOREIGN KEY (color_id) REFERENCES Colors (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ItemTags (
  item_id INTEGER,
  tag_id INTEGER,
  PRIMARY KEY (item_id, tag_id),
  FOREIGN KEY (item_id) REFERENCES Items (id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES Tags (id) ON DELETE CASCADE
);

-- status: активная | архивная | черновик
-- type: постоянная | временная
CREATE TABLE IF NOT EXISTS Capsules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  start_date TEXT,
  end_date TEXT,
  status TEXT DEFAULT 'активная' CHECK (status IN ('активная', 'архивная', 'черновик')),
  type TEXT DEFAULT 'постоянная' CHECK (type IN ('постоянная', 'временная'))
);

CREATE TABLE IF NOT EXISTS CapsuleItems (
  capsule_id INTEGER,
  item_id INTEGER,
  packing_status TEXT DEFAULT 'не упаковано',
  PRIMARY KEY (capsule_id, item_id),
  FOREIGN KEY (capsule_id) REFERENCES Capsules (id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES Items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS Filters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  filter_type TEXT
);

CREATE TABLE IF NOT EXISTS CategoryFilterValues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category_id INTEGER,
  filter_id INTEGER,
  value TEXT,
  FOREIGN KEY (category_id) REFERENCES Categories (id) ON DELETE CASCADE,
  FOREIGN KEY (filter_id) REFERENCES Filters (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SavedFilterSets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  criteria_json TEXT NOT NULL,
  date_created TEXT DEFAULT CURRENT_TIMESTAMP,
  date_modified TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_items_category_id ON Items (category_id);
CREATE INDEX IF NOT EXISTS idx_items_status_id ON Items (status_id);
CREATE INDEX IF NOT EXISTS idx_items_date_created ON Items (date_created);
CREATE INDEX IF NOT EXISTS idx_tags_name ON Tags (name);
CREATE INDEX IF NOT EXISTS idx_item_tags_tag_id ON ItemTags (tag_id);
CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON Categories (parent_id);
CREATE INDEX IF NOT EXISTS idx_saved_filter_sets_name ON SavedFilterSets (name);

-- Reference data (idempotent)

INSERT OR IGNORE INTO ItemStatuses (name) VALUES ('в использовании');
INSERT OR IGNORE INTO ItemStatuses (name) VALUES ('на хранении');
INSERT OR IGNORE INTO ItemStatuses (name) VALUES ('на выброс/в переработку');
INSERT OR IGNORE INTO ItemStatuses (name) VALUES ('потеряна/отдана');

INSERT OR IGNORE INTO Categories (name) VALUES ('верхняя одежда');
INSERT OR IGNORE INTO Categories (name) VALUES ('обувь');
INSERT OR IGNORE INTO Categories (name) VALUES ('нижняя одежда');
INSERT OR IGNORE INTO Categories (name) VALUES ('аксессуары');

INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Чёрный', '#000000');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Белый', '#FFFFFF');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Серый', '#808080');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Тёмно-серый', '#A9A9A9');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Светло-серый', '#D3D3D3');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Бежевый', '#F5F5DC');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Кремовый', '#FFFDD0');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Слоновая кость', '#FFFFF0');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Коричневый', '#A52A2A');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Тёмно-коричневый', '#654321');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Синий', '#0000FF');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Тёмно-синий', '#000080');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Голубой', '#ADD8E6');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Небесно-голубой', '#87CEEB');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Бирюзовый', '#40E0D0');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Индиго', '#4B0082');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Васильковый', '#6495ED');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Зелёный', '#008000');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Тёмно-зелёный', '#006400');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Оливковый', '#808000');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Мятный', '#98FF98');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Изумрудный', '#50C878');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Салатовый', '#99FF99');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Красный', '#FF0000');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Бордовый', '#800000');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Винный', '#722F37');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Алый', '#FF2400');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Розовый', '#FFC0CB');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Пудровый', '#FDE9E0');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Коралловый', '#FF7F50');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Фуксия', '#FF00FF');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Жёлтый', '#FFFF00');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Горчичный', '#FFDB58');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Оранжевый', '#FFA500');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Персиковый', '#FFDAB9');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Фиолетовый', '#800080');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Сиреневый', '#C8A2C8');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Лавандовый', '#E6E6FA');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Песочный', '#C2B280');
INSERT OR IGNORE INTO Colors (name, hex_code) VALUES ('Хаки', '#C3B091');

INSERT OR IGNORE INTO Tags (name, color_id)
VALUES ('Домашнее', (SELECT id FROM Colors WHERE name = 'Светло-серый'));
INSERT OR IGNORE INTO Tags (name, color_id)
VALUES ('Выходное', (SELECT id FROM Colors WHERE name = 'Красный'));
INSERT OR IGNORE INTO Tags (name, color_id)
VALUES ('Парадное', (SELECT id FROM Colors WHERE name = 'Жёлтый'));
INSERT OR IGNORE INTO Tags (name, color_id)
VALUES ('Деловое', (SELECT id FROM Colors WHERE name = 'Тёмно-синий'));
INSERT OR IGNORE INTO Tags (name, color_id)
VALUES ('На выброс', (SELECT id FROM Colors WHERE name = 'Коричневый'));

DELETE FROM Colors
WHERE id NOT IN (
  SELECT MIN(id)
  FROM Colors
  GROUP BY name
);

INSERT OR IGNORE INTO schema_migrations (version) VALUES (1);
